#+TITLE: Installing archlinux with encrypted disk
#+DATE:2016-12-03
#+STARTUP:showeverything

* Introduction
This is a small manual for installing Arch Linux. In this manual Arch
will be installed on a separate USB drive for booting Arch Linux on a
MacBook Air (without touching the internal disk).

* Preparation

** Download archlinux
Archlinux can be downloaded from [[https://www.archlinux.org/download/][archlinux.org]], either a BitTorrent
download or a direct HTTP download. Once downloaded, the download's
integrity should be verified. For this the signature also has to be
downloaded, e.g. [[https://www.archlinux.org/iso/2016.12.01/archlinux-2016.12.01-dual.iso.sig][archlinux-2016.12.01-dual.iso.sig]] (of the same file
ofcourse). Once both the download and the signature reside in the same
directory, verification can be done like so:
#+BEGIN_SRC shell
$ gpg --keyserver-options auto-key-retrieve --verify archlinux-<version>-dual.iso.sig
#+END_SRC

Note that this command gave me a failed verification with a warning on
Debian Jessie, because of not being able to find the public key. I
guess the auto-key-retrieve on Debian doesn't work like it does on Arch.

Or, if you're already running Arch, you can do:
#+BEGIN_SRC shell
pacman-key -v archlinux-<version>-dual.iso.sig
#+END_SRC

** Prepare installation media
The location of your USB drive can be determined by =dmesg= (right
after insterting it) or by =lsblk=.
#+BEGIN_SRC shell
# dd bs=4M if=/path/to/archlinux.iso of=/dev/sdx status=progress && sync
#+END_SRC

The =sync= is there to make sure all data is written to the drive
prior to removing it from your computer.

* Booting from the installation media
So the USB drive has been prepared, so connect it to the MacBook Air
and power cycle the laptop. Just before the mac is booting you must
press the right 'option' key (alt) until the boot menu is shown. It
should at least show your normal `Macintosh HD' and an extra `EFI
Boot', the latter being the Arch Linux installer. Select it using the
arrow keys and press =enter=. Arch will boot!

After a few seconds a shell is shown, I'm automatically logged into
the installer as =root=. Since we're on Mac, it should have booted in
EFI mode, lets check:
#+BEGIN_SRC shell
# ls /sys/firmware/efi/efivars
#+END_SRC

If this directory doens't exist, it'll have booted in BIOS mode.

The Arch Linux wiki now suggests working on the network configuration,
but since I'm on wifi on a Mac, I prefer to do that later.

** Partition the USB drive
Now I'm going to prepare the USB drive that I'm going to use for
Arch. It's a 64GB SanDisk Extreme drive, connected via USB 3.0, it
won't be as fast as the Mac's internal SSD but that's ok.

The Arch Linux wiki has a lot of information on disk encryption, check
[[https://wiki.archlinux.org/index.php/Disk_encryption][here]]. I'm going to use dm-crypt together with LVM. There are basically
two ways to go about this:
- install LVM on top of the encryption layer.
- create an encyption layer on top of LVM.
Since I'm using a single USB drive on which Arch is going to be
installed, I'll choose the somewhat easer approach (the first one). 

The following partitions will be put on the drive:
- EFI System Partition (ESP) [512M]
- Linux filesystem [1G, /boot]
- LVM [62G]
  - swap [4G]
  - root [58G]

